Repository ingenieria-software-7009-2025-2/city-lens-front-end, pull requests merged in 2025-03, with the labels that each got.

#5 refactor: CODEOWNERS reubicado a .github/
  .github/CODEOWNERS
  CODEOWNERS
Labels: refactor

#2 feat: archivos base para el proyecto usando vite + react
  .gitignore
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/assets/images/breakdown.ico
  src/assets/images/react.svg
  src/assets/images/vite.svg
  src/index.css
  src/main.jsx
  vite.config.js
Labels: enhancement

#4 Organizacion proyecto
  LICENSE
  README.md
  eslint.config.js
  package-lock.json
  src/App.tsx
  src/assets/styles/app.scss
  src/assets/styles/index.scss
  src/components/Layout/components/Label/Label.scss
  src/components/Layout/components/Label/Label.tsx
  src/components/UI/Button/Button.scss
  src/components/UI/Button/Button.tsx
  src/components/UI/Button/tests/Button.test.tsx
  src/components/UI/Form/Form.tsx
  src/components/UI/Form/form.module.scss
  src/components/UI/Input/Input.scss
  src/components/UI/Input/Input.tsx
  src/components/UI/Label/Label.tsx
  src/components/UI/Label/label.scss
  src/components/UI/index.ts
  src/main.tsx
  src/pages/Login/Login.module.scss
  src/pages/Login/Login.tsx
  src/pages/Login/index.ts
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: refactor

#7 feat(tar-9): archivos base de React + Vite
  .github/CODEOWNERS
  .gitignore
  CODEOWNERS
  LICENSE
  README.md
  docs/guides/organizacion_directorios.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/App.tsx
  src/assets/images/breakdown.ico
  src/assets/images/react.svg
  src/assets/images/vite.svg
  src/assets/styles/app.scss
  src/assets/styles/index.scss
  src/components/Layout/components/Label/Label.scss
  src/components/Layout/components/Label/Label.tsx
  src/components/UI/Button/Button.scss
  src/components/UI/Button/Button.tsx
  src/components/UI/Button/tests/Button.test.tsx
  src/components/UI/Form/Form.tsx
  src/components/UI/Form/form.module.scss
  src/components/UI/Input/Input.scss
  src/components/UI/Input/Input.tsx
  src/components/UI/Label/Label.tsx
  src/components/UI/Label/label.scss
  src/components/UI/index.ts
  src/index.css
  src/main.jsx
  src/main.tsx
  src/pages/Login/Login.module.scss
  src/pages/Login/Login.tsx
  src/pages/Login/index.ts
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.js
  vite.config.ts
Labels: enhancement

#8 docs(tar19): plantillas para issues y reporte de bugs
  .github/ISSUE_TEMPLATE/petición-sugerencia-de-funcionalidad-.md
  .github/ISSUE_TEMPLATE/reporte-de-bug.md
Labels: documentation

#6 Creacion de login
  src/assets/images/City Background GIF.gif
  src/assets/images/city.jpg
  src/assets/images/overlay.jpeg
  src/assets/styles/app.scss
  src/assets/styles/index.scss
  src/components/Layout/components/Label/Label.scss
  src/components/Layout/components/Label/Label.tsx
  src/components/UI/Button/Button.scss
  src/components/UI/Button/Button.tsx
  src/components/UI/Form/Form.tsx
  src/components/UI/Form/form.module.scss
  src/components/UI/Input/Input.scss
  src/components/UI/Input/Input.tsx
  src/components/UI/Label/Label.tsx
  src/components/UI/Label/label.scss
  src/pages/Login/Login.module.scss
  src/pages/Login/Login.tsx
Labels: enhancement

#13 fix(tar35): correción de archivos conflictivos paso a typescript
  .run/dev.run.xml
  package-lock.json
  package.json
  src/App.tsx
  src/api/config/axios.ts
  src/components/ui/button/button.scss
  src/components/ui/button/button.tsx
  src/components/ui/button/tests/button.test.tsx
  src/components/ui/form/form.module.scss
  src/components/ui/form/form.tsx
  src/components/ui/index.ts
  src/components/ui/input/input.scss
  src/components/ui/input/input.tsx
  src/components/ui/label/label.scss
  src/components/ui/label/label.tsx
  src/main.tsx
  src/pages/login/index.ts
  src/pages/login/login.module.scss
  src/pages/login/login.tsx
Labels: bug

#16 docs(tar-31):Documentacion de casos de usos
  docs/automatic_framework_info.md
  docs/v.0.1/readme_v01.md
  docs/v.1.0/CasosDeUso.pdf
  docs/v.1.0/Diagramas/DF_ActualizarDatos.png
  docs/v.1.0/Diagramas/DF_CerrarSesion.png
  docs/v.1.0/Diagramas/DF_ConsultarInfo.png
  docs/v.1.0/Diagramas/DF_InicioSesion.png
  docs/v.1.0/Diagramas/DF_RegistrarSesion.png
  docs/v.1.0/Diagramas/DiagramaUML.png
Labels: documentation

#18 docs(tar22): documentación general del frontend
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/petición-sugerencia-de-funcionalidad-.md
  .github/ISSUE_TEMPLATE/reporte-de-bug.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .gitignore
  .run/dev.run.xml
  .run/storybook.run.xml
  .storybook/main.ts
  .storybook/preview.ts
  README.md
  docs/guides/organizacion_directorios.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/api/config/axios.ts
  src/api/index.ts
  src/api/models/auth.ts
  src/api/services/auth.ts
  src/assets/styles/app.scss
  src/components/ui/button/button.scss
  src/components/ui/button/button.stories.tsx
  src/components/ui/button/button.tsx
  src/components/ui/button/tests/button.test.tsx
  src/components/ui/form/form.module.scss
  src/components/ui/form/form.stories.tsx
  src/components/ui/form/form.tsx
  src/components/ui/index.ts
  src/components/ui/input/input.scss
  src/components/ui/input/input.stories.tsx
  src/components/ui/input/input.tsx
  src/components/ui/label/label.scss
  src/components/ui/label/label.stories.tsx
  src/components/ui/label/label.tsx
  src/main.tsx
  src/pages/login/index.ts
  src/pages/login/login.module.scss
  src/pages/login/login.tsx
  src/pages/menu/index.ts
  src/pages/menu/menu.module.scss
  src/pages/menu/menu.tsx
  src/stories/Configure.mdx
  src/stories/assets/github.svg
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/readme_storybook.md
  tsconfig.app.json
  tsconfig.node.json
  vite.config.js
  vite.config.ts
Labels: documentation

#20 tar42-styling-wallsified
  .storybook/main.ts
  README.md
  docs/v.0.1/readme_v01.md
  index.html
  src/App.tsx
  src/api/config/axios.ts
  src/api/services/auth.ts
  src/assets/styles/app.scss
  src/assets/styles/index.scss
  src/components/Layout/Nav/nav.scss
  src/components/Layout/Nav/nav.tsx
  src/components/others/ProtectedRoute/protectedroute.tsx
  src/components/ui/button/button.stories.tsx
  src/components/ui/form/form.stories.tsx
  src/components/ui/input/input.stories.tsx
  src/components/ui/label/label.stories.tsx
  src/context/AuthContext.tsx
  src/pages/edit/edit.module.scss
  src/pages/edit/edit.tsx
  src/pages/edit/index.ts
  src/pages/login/login.tsx
  src/pages/menu/menu.module.scss
  src/pages/menu/menu.tsx
  src/stories/Configure.mdx
  src/stories/readme_storybook.md
Labels: refactor

#22 fix/docs: información faltante en readme
  README.md
Labels: documentation
